---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[wombat-oam::default]
    attributes:
      wombat_oam:
        otp_name: wombat@127.0.0.1
